package com.kwesou.hardwarespoof.config;

import java.util.Arrays;
import java.util.List;

public class gpuList {
    public static List<String> listofGPUs = Arrays.asList(
            "Intel(R) HD Graphics 510",
            "Intel(R) HD Graphics 515",
            "Intel(R) HD Graphics 520",
            "Intel(R) HD Graphics 530",
            "Intel(R) Iris(R) Graphics 540",
            "Intel(R) Iris(R) Graphics 550",
            "Intel(R) Iris(R) Graphics 580",
            "Intel(R) UHD Graphics 600",
            "Intel(R) UHD Graphics 605",
            "Intel(R) HD Graphics 610",
            "Intel(R) HD Graphics 615",
            "Intel(R) HD Graphics 620",
            "Intel(R) HD Graphics 630",
            "Intel(R) Iris(R) Plus Graphics 640",
            "Intel(R) Iris(R) Plus Graphics 650",
            "Intel(R) UHD Graphics 600",
            "Intel(R) UHD Graphics 605",
            "Intel(R) UHD Graphics 610",
            "Intel(R) UHD Graphics 615",
            "Intel(R) UHD Graphics 617",
            "Intel(R) UHD Graphics 620",
            "Intel(R) UHD Graphics 630",
            "Intel(R) UHD Graphics 645",
            "Intel(R) UHD Graphics 655",
            "Intel(R) UHD Graphics 710",
            "Intel(R) UHD Graphics 730",
            "Intel(R) UHD Graphics 750",
            "Intel(R) UHD Graphics 770",
            "Intel(R) Iris(R) Xe Graphics",
            "Intel(R) Arc(TM) B580",
            "Intel(R) Arc(TM) B570",
            "Intel(R) Arc(TM) A770",
            "Intel(R) Arc(TM) A750",
            "Intel(R) Arc(TM) A580",
            "Intel(R) Arc(TM) A380",
            "Intel(R) Arc(TM) A310",
            "AMD Radeon RX 5500",
            "AMD Radeon RX 5500 XT",
            "AMD Radeon RX 5600 XT",
            "AMD Radeon RX 5700",
            "AMD Radeon RX 5700 XT",
            "AMD Radeon RX 6400",
            "AMD Radeon RX 6500 XT",
            "AMD Radeon RX 6600",
            "AMD Radeon RX 6600 XT",
            "AMD Radeon RX 6650 XT",
            "AMD Radeon RX 6700",
            "AMD Radeon RX 6700 XT",
            "AMD Radeon RX 6750 XT",
            "AMD Radeon RX 6800",
            "AMD Radeon RX 6800 XT",
            "AMD Radeon RX 6850 XT",
            "AMD Radeon RX 6900 XT",
            "AMD Radeon RX 6950 XT",
            "AMD Radeon RX 7600",
            "AMD Radeon RX 7600 XT",
            "AMD Radeon RX 7700 XT",
            "AMD Radeon RX 7800 XT",
            "AMD Radeon RX 7900 GRE",
            "AMD Radeon RX 7900 XT",
            "AMD Radeon RX 7900 XTX",
            "AMD Radeon RX 460",
            "AMD Radeon RX 470",
            "AMD Radeon RX 480",
            "AMD Radeon RX 550",
            "AMD Radeon RX 560",
            "AMD Radeon RX 570",
            "AMD Radeon RX 580",
            "AMD Radeon RX 590",
            "AMD Radeon RX Vega 56",
            "AMD Radeon RX Vega 64",
            "AMD Radeon RX 5500M",
            "AMD Radeon RX 5600M",
            "AMD Radeon RX 5700M",
            "AMD Radeon RX 6300M",
            "AMD Radeon RX 6500M",
            "AMD Radeon RX 6600M",
            "AMD Radeon RX 6700M",
            "AMD Radeon RX 6800M",
            "AMD Radeon RX 7600M",
            "AMD Radeon RX 7700M",
            "AMD Radeon RX 7800M",
            "AMD Radeon RX 7900M",
            "AMD Radeon Vega 3 Mobile",
            "AMD Radeon Vega 6 Mobile",
            "AMD Radeon Vega 8 Mobile",
            "AMD Radeon Vega 9 Mobile",
            "AMD Radeon Vega 10 Mobile",
            "AMD Radeon RX Vega 56 Mobile",
            "AMD Radeon Vega 3",
            "AMD Radeon Vega 6",
            "AMD Radeon Vega 7",
            "AMD Radeon Vega 8",
            "AMD Radeon Vega 10",
            "AMD Radeon Vega 11",
            "AMD Radeon 610M",
            "AMD Radeon 660M",
            "AMD Radeon 680M",
            "AMD Radeon 740M",
            "AMD Radeon 760M",
            "AMD Radeon 780M",
            "NVIDIA GeForce RTX 4090/PCIe/SSE2",
            "NVIDIA GeForce RTX 4080/PCIe/SSE2",
            "NVIDIA GeForce RTX 4070 Ti Super/PCIe/SSE2",
            "NVIDIA GeForce RTX 4070 Ti/PCIe/SSE2",
            "NVIDIA GeForce RTX 4070 Super/PCIe/SSE2",
            "NVIDIA GeForce RTX 4070/PCIe/SSE2",
            "NVIDIA GeForce RTX 4060 Ti/PCIe/SSE2",
            "NVIDIA GeForce RTX 4060/PCIe/SSE2",
            "NVIDIA GeForce RTX 3090 Ti/PCIe/SSE2",
            "NVIDIA GeForce RTX 3090/PCIe/SSE2",
            "NVIDIA GeForce RTX 3080 Ti/PCIe/SSE2",
            "NVIDIA GeForce RTX 3080/PCIe/SSE2",
            "NVIDIA GeForce RTX 3070 Ti/PCIe/SSE2",
            "NVIDIA GeForce RTX 3070/PCIe/SSE2",
            "NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2",
            "NVIDIA GeForce RTX 3060/PCIe/SSE2",
            "GeForce GTX 1660 Ti/PCIe/SSE2",
            "GeForce GTX 1660 Super/PCIe/SSE2",
            "GeForce GTX 1660/PCIe/SSE2",
            "GeForce GTX 1650 Super/PCIe/SSE2",
            "GeForce GTX 1650/PCIe/SSE2",
            "GeForce GTX 1080/PCIe/SSE2",
            "GeForce GTX 1080 Ti/PCIe/SSE2",
            "GeForce GTX 1070 Ti/PCIe/SSE2",
            "GeForce GTX 1070/PCIe/SSE2",
            "GeForce GTX 1060 6GB/PCIe/SSE2",
            "GeForce GTX 1060 3GB/PCIe/SSE2",
            "GeForce GTX 1060 5GB/PCIe/SSE2",
            "GeForce GTX 1050 Ti/PCIe/SSE2",
            "GeForce GTX 1050/PCIe/SSE2",
            "GeForce GTX 1080 Ti/PCIe/SSE2",
            "GeForce GTX 750 Ti/PCIe/SSE2",
            "GeForce GT 710/PCIe/SSE2",
            "GeForce GT 730/PCIe/SSE2",
            "GeForce GT 1030/PCIe/SSE2",
            "GeForce GT 1010/PCIe/SSE2"
    );
}
